# Reply to issue creation based on type of message opened
name: Welcome New Contributor

on:
  issues:
    types:
      - labeled

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new proposition
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b
        if: github.event.label.name == '📄 Grant application'
        with:
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello  _**${{ github.event.issue.user.login }}**_,

            Thank you for your Grant application! Our team will review and add comments in your issue! In the meantime:
            1. Join the [FHE.org discord server](https://discord.fhe.org/) for any questions (pick the Zama library channel you will use).
            2. Ask questions privately: [bounty@zama.ai](mailto:bounty@zama.ai).
